server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lmsproject
    username: postgres
    password: 295008k
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update